name:                echobot
version:             0.1.0.0
github:              "wspbr/echobot"
license:             BSD3
author:              "Oleg Pascal"
maintainer:          "rtrn.0@ya.ru"
copyright:           "2020 Oleg Pascal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wspbr/echobot#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- mtl
- text
- time
- template-haskell
- hspec
- hspec-discover
- QuickCheck
- quickcheck-instances
- configurator
- random
- servant
- servant-client
- http-client
- http-client-tls
- co-log
- unordered-containers
- directory
- pretty-simple

library:
  source-dirs: src

executables:
  echobot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-orphans
    dependencies:
    - echobot

tests:
  echobot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echobot
